output_basedir: "$HOME/.local/share/pcabinet"
services:
  - name: this
    endpoint: http://127.0.0.1:8080/debug/pprof
  - name: that
    endpoint: http://127.0.0.1:8080/debug/pprof
  - name: something-else
    endpoint: http://127.0.0.1:8080/debug/pprof